name: Register
version: 1.7
main: com.nijikokun.register.Register
description: >
             Register, an API built for economies.
authors: [Nijikokun, LRFLEW, Acrobot, miho, Snowleo, KHobbits, Spice-King, ElgarL]
website: https://github.com/ElgarL/Register
softdepend: [iConomy, BOSEconomy, Currency, MultiCurrency, Craftconomy]